### PR TITLE
fix(otelgorm): restore original context in "after" callback

### LINKED ISSUE #84: otelgorm replaces (but does not restore) context from statement
The otelgorm package utilizes replacement the statement context when the `before` is called...

https://github.com/uptrace/opentelemetry-go-extra/blob/fcc6618cc37ccf42377873b4b898db73c5081384/otelgorm/otelgorm.go#L97-L101

However, the statement context is never restored to its original in the corresponding `after()` call. Thus, after the execution of the query finishes, if the `db.Statement` object is reused, then the context of the statement will still be using the context corresponding to the now-ended span.

The following is a failing test case:

```golang
  {
    do: func(ctx context.Context, db *gorm.DB) {
      var count int64
      query := db.WithContext(ctx).Table("generate_series(1, 10)")
      _, _ = query.Select("*").Rows()
      _ = query.Count(&count)
    },
    require: func(t *testing.T, spans []sdktrace.ReadOnlySpan) {
      require.Equal(t, 2, len(spans))
      require.Equal(
        t,
        spans[0].Parent().SpanID().String(),
        spans[1].Parent().SpanID().String(),
      )
    },
  }
```

In `do`, you can see two separate queries being run (with `Rows()` and `Count()`). To me, the spans generated for these two queries should have the same parent. Instead, otelgorm is making the span of the second query a child of the first. If I added a third execution using the `query` value, that span would be a child of the second. Ideally, the plugin would restore the statement back to it's original so the statement could be reused.

The only way I could think of doing this was to store the original context in the newly derived context, and then during the `after` callback pop it out. But that seemed error prone given that Gorm doesn't enforce the ordering of callbacks, so we'd have to hope another callback isn't trying to do the same thing but with a different ordering.

### PR DESCRIPTION
**Pull request by markhildreth-gravity**
**This PR**

Ensures that the `tx.Statement.Context` value that was present when the `before` callback is called is restored after the `after` callback is finished. This fixes #84, which would cause subsequent queries built using the same statement to be seen in children spans.

**Why**

Issue #84 explains how, when the same statement is used for multiple executions, then each execution will be created in a span that is seen as a child of the last. This can often happen when a user of gorm make a query using the query builder API, runs the query, then continues using the original builder to run a slightly modified version of the query.

Below shows an example of the problems this causes. The last three query spans are seen as children to the query before it, when in actuality only the final two should have a parent-child relationship (due to the final query being an eager load).

image

When using this branch, the context is restored and thus the lineage is correct. The below image shows the results.

image

**Note:** Failures appear to be due to main branch.

### CODE REVIEW

File: otelgorm/internal/e2etest/e2e_test.go [hunk 1]
```diff
@@ -93,6 +93,22 @@ func TestEndToEnd(t *testing.T) {
 				require.Equal(t, 1, len(spans))
 			},
 		},
+		{
+			do: func(ctx context.Context, db *gorm.DB) {
```
Comment (markhildreth-gravity) [inline otelgorm/internal/e2etest/e2e_test.go:97]: Just noticed that I could leave off the `options` I added in the prior PR when no options are needed since the array would just default to empty.

**Comment by vmihailenco** [comment]
Thanks :+1:
